### ISSUE TITLE
Improve your survey question comprehension in codelab- Moving Augmented Images -https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#0

### ISSUE THREAD

**Issue by hmaw** [googlecodelabs/arcore-augmentedimage-intro#1]
Page of this issue:
https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#0

The text of the second question in this codelab asks:  "Do you plan to write sample code in this codelab or just want to read these pages?" and the answer is a "Yes or No"   The format of the question needs to be modified to make it able to be understood better by the reader. 

Suggested fix : remake the question to "Do you plan to write sample code in this codelab?  Choose "No" if you just want to read these pages.

**Comment by kai-dream** [comment]
Nice catch! Thanks, I'll update the site.

**Comment by kai-dream** [comment]
Done.
