### ISSUE TITLE
the requirement of devices

### ISSUE THREAD

**Issue by Wilfred-Yang** [googlecodelabs/arcore-augmentedimage-intro#10]
Hi, I want to use the real device to test Augmented Images. 

I reference this link: https://developers.google.com/ar/discover/supported-devices.

However, there is a list called "Notes" which shows something like Supports Depth API, Supports multiple GPU texture resolutions - 1080p, 720p, 480p, and so on. 

I don't know whether Augmented Images in ARcore needs functions in Notes or not. Could you tell me what kind of functions does the device need to support Augmented Images in ARcore. I need to choose a right device.

**Comment by kai-dream** [comment]
Hi

Thanks for the question,

AugmentedImage feature is in the basic feature set in ARCore, it doesn't require any of the additional features in "Notes" section. You can choose any ARCore devices for testing purpose.

Kai

**Comment by Wilfred-Yang** [comment]
Thank you so much for your answer!!
