### ISSUE TITLE
Additional issues in "ARCore Augmented Images" codelab

### ISSUE THREAD

**Issue by hbodasing** [googlecodelabs/arcore-augmentedimage-intro#12]
Hi,

Below are suggestions for improving the ARCore Augmented Images codelab, along with details of issues that I encountered:

Step 4:
I suggest adding a note that the specified updateModelMatrix() code should be added as a new function rather than replacing the existing updateModelMatrix() (replacing the function causes errors)

Step 5:
The user is asked to add code to AugmentedImageNode.java, but this file has not been supplied. As stated in issue #8, the code needs to added to AugmentedImageRenderer.java instead so suggest updating the codelab accordingly.

Step 6:
The PhysicsController.java file contains build errors; these can be fixed as follows:
a) Update package name: replace
package com.google.ar.sceneform.samples.augmentedimage;
with 
package com.google.ar.core.examples.java.augmentedimage;

b) Remove the following lines:
import com.google.ar.sceneform.math.Quaternion;
import com.google.ar.sceneform.math.Vector3;

c) Do Build->Rebuild Project to install jBullet and resolve PhysicsController.java errors

Hope this helps,

Hemal.

**Comment by kai-dream** [comment]
Hi,

Thanks for your suggestion. Your suggestion are great. The codelab was originally for sceneform SDK, then ported to Java SDK, so I probably missed a few places to update. Updating the codelab is not very straightforward at the moment, but I'll add your suggestions to the home page for now.


Cheers
Kai

**Comment by kai-dream** [comment]
I added a note in https://github.com/googlecodelabs/arcore-augmentedimage-intro/commit/33be4ecb3997b54c91416461fdb5973d30ed54dd

**Comment by hbodasing** [comment]
Hi Kai,
Thanks for getting back to me; I’m glad you found the suggestions useful.
I appreciate that updating the codelab is tricky, but look forward to seeing the new version when it’s ready.
Cheers,
Hemal.


    On Monday, 25 January 2021, 07:51:51 GMT, kai-dream <notifications@github.com> wrote:  
 
 


Hi,

Thanks for your suggestion. Your suggestion are great. The codelab was originally for sceneform SDK, then ported to Java SDK, so I probably missed a few places to update. Updating the codelab is not very straightforward at the moment, but I'll add your suggestions to the home page for now.

Cheers
Kai

**Comment by hbodasing** [comment]
Hi Kai,
Hope all’s well.
Just letting you know that I’ll be presenting your codelab at a Google Developer Group event tomorrow (Thu 11th Feb) at 7pm UK time. You’re extremely welcome to attend; details here:https://gdg.community.dev/events/details/google-gdg-london-presents-gdg-devparty-uki-arcore-augmented-images/#/

Kind regards,
Hemal.


    On Tuesday, 26 January 2021, 09:45:20 GMT, Hemal Bodasing <hbodasing@yahoo.co.uk> wrote:  
 
  Hi Kai,
Thanks for getting back to me; I’m glad you found the suggestions useful.
I appreciate that updating the codelab is tricky, but look forward to seeing the new version when it’s ready.
Cheers,
Hemal.


    On Monday, 25 January 2021, 07:51:51 GMT, kai-dream <notifications@github.com> wrote:  
 
 


Hi,

Thanks for your suggestion. Your suggestion are great. The codelab was originally for sceneform SDK, then ported to Java SDK, so I probably missed a few places to update. Updating the codelab is not very straightforward at the moment, but I'll add your suggestions to the home page for now.

Cheers
Kai

**Comment by kai-dream** [comment]
Thanks for the heads up! I hope it goes well, and please let me know if you encounter problems in the codelab.

**Comment by kai-dream** [comment]
Hi,

I've updated the codelab addressed all the issues the you reported. Thanks for providing the reminders!

> Step 4:
> I suggest adding a note that the specified updateModelMatrix() code should be added as a new function rather than replacing the existing updateModelMatrix() (replacing the function causes errors)

Kai: Added notes to explain this.

> Step 5:
> The user is asked to add code to AugmentedImageNode.java, but this file has not been supplied. As stated in issue #8, the code needs to added to AugmentedImageRenderer.java instead so suggest updating the codelab accordingly.
> 

Kai: Updated. Thanks for reminding!

> Step 6:
> The PhysicsController.java file contains build errors; these can be fixed as follows:
> a) Update package name: replace
> package com.google.ar.sceneform.samples.augmentedimage;
> with
> package com.google.ar.core.examples.java.augmentedimage;
> 
> b) Remove the following lines:
> import com.google.ar.sceneform.math.Quaternion;
> import com.google.ar.sceneform.math.Vector3;
> 
> c) Do Build->Rebuild Project to install jBullet and resolve PhysicsController.java errors
> 

Kai: Updated PhysicsController.java link in codelab description. The link was out-of-date, even though I updated the file in Github. Sorry for the confusion. And good job you fixed those building errors yourself!
