### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by bitamirshafiee** [googlecodelabs/arcore-augmentedimage-intro#13]
Hello,
I followed the example, in code lab, and checked the code here too, and it seems everything is right, but when the planet detected and we have the maze on it, the Andy will be appeared but it will fall down and not moving in the maze. I have no idea what could be the problem. and everything is as supposed to be. Do you have any idea for what this is happening?or where should I take a close look at?

here is the code for AugmentedImageRenderer:

```
 public void draw(
          float[] viewMatrix,
          float[] projectionMatrix,
          AugmentedImage augmentedImage,
          Anchor centerAnchor,
          float[] colorCorrectionRgba) {
    float[] tintColor =
            convertHexToColor(TINT_COLORS_HEX[augmentedImage.getIndex() % TINT_COLORS_HEX.length]);

    final float mazeEdgeSize = 492.65f; // Magic number of maze size
    final float maxImageEdgeSize = Math.max(augmentedImage.getExtentX(), augmentedImage.getExtentZ()); // Get largest detected image edge size

    Pose anchorPose = centerAnchor.getPose();

    float mazeScaleFactor = maxImageEdgeSize / mazeEdgeSize; // scale to set Maze to image size
    float[] modelMatrix = new float[16];

    // OpenGL Matrix operation is in the order: Scale, rotation and Translation
    // So the manual adjustment is after scale
    // The 251.3f and 129.0f is magic number from the maze obj file
    // You mustWe need to do this adjustment because the maze OBJobj file
    // is not centered around origin. Normally when you
    // work with your own model, you don't have this problem.
    Pose mazeModelLocalOffset = Pose.makeTranslation(
            -251.3f * mazeScaleFactor,
            0.0f,
            129.0f * mazeScaleFactor);
    anchorPose.compose(mazeModelLocalOffset).toMatrix(modelMatrix, 0);
    mazeRenderer.updateModelMatrix(modelMatrix, mazeScaleFactor, mazeScaleFactor/10.0f, mazeScaleFactor); // This line relies on a change in ObjectRenderer.updateModelMatrix later in this codelab.
    mazeRenderer.draw(viewMatrix, projectionMatrix, colorCorrectionRgba, tintColor);

    // Adjust the Andy's rendering position
    // The Andy's pose is at the maze's vertex's coordinate
    Pose andyPoseInImageSpace = Pose.makeTranslation(
            andyPose.tx() * mazeScaleFactor,
            andyPose.ty() * mazeScaleFactor,
            andyPose.tz() * mazeScaleFactor);

    anchorPose.compose(andyPoseInImageSpace).toMatrix(modelMatrix, 0);
    andyRenderer.updateModelMatrix(modelMatrix, 0.05f);
    andyRenderer.draw(viewMatrix, projectionMatrix, colorCorrectionRgba, tintColor);

  }

  public void updateAndyPose(Pose pose) {
    andyPose = pose;
  }
public void updateAndyPose(Pose pose) {
    andyPose = pose;
  }

```

and here for AugmentedImageActivity:

`private void drawAugmentedImages(
          Frame frame, float[] projmtx, float[] viewmtx, float[] colorCorrectionRgba) {
    Collection<AugmentedImage> updatedAugmentedImages =
            frame.getUpdatedTrackables(AugmentedImage.class);

    // Iterate to update augmentedImageMap, remove elements we cannot draw.
    for (AugmentedImage augmentedImage : updatedAugmentedImages) {
      switch (augmentedImage.getTrackingState()) {
        case PAUSED:
          // When an image is in PAUSED state, but the camera is not PAUSED, it has been detected,
          // but not yet tracked.
          String text = String.format("Detected Image %d", augmentedImage.getIndex());
          messageSnackbarHelper.showMessage(this, text);
          break;

        case TRACKING:
          // Switch to UI Thread to update View
          this.runOnUiThread(
                  new Runnable() {
                    @Override
                    public void run() {
                      fitToScanView.setVisibility(View.GONE);
                    }
                  });

          // Create a new anchor for newly found images
          if (!augmentedImageMap.containsKey(augmentedImage.getIndex())) {
            Anchor centerPoseAnchor = augmentedImage.createAnchor(augmentedImage.getCenterPose());
            augmentedImageMap.put(
                    augmentedImage.getIndex(), Pair.create(augmentedImage, centerPoseAnchor));

            physicsController = new PhysicsController(this);
          } else {
            Pose ballPose = physicsController.getBallPose();
            augmentedImageRenderer.updateAndyPose(ballPose);

            // Use real world gravity, (0, -10, 0), as gravity
            // Convert to Physics world coordinate(maze mesh has to be static)
            // Use it as a force to move the ball
            Pose worldGravityPose = Pose.makeTranslation(0, -10f, 0);
            Pose mazeGravityPose = augmentedImage.getCenterPose().inverse().compose(worldGravityPose);
            float[] mazeGravity = mazeGravityPose.getTranslation();
            physicsController.applyGravityToBall(mazeGravity);

            physicsController.updatePhysics();
          }
          break;

        case STOPPED:
          augmentedImageMap.remove(augmentedImage.getIndex());
          break;

        default:
          break;
      }
    }`

**Comment by kai-dream** [comment]
Hi,

I guess, maybe your earth image is placed vertically, for example, on a monitor screen?

If so, then it's normal for the Android to fall down. Because I used the real world gravity to move the android. You need an earth image that's placed on a horizontal flag plane, for example on top of a book.

If you want to debug it, I think a good place will be printing out log messages in AugmentedImageActivity.drawAugmentedImages() function. For example, reduce the worldGravityPose to (0, -0.1f, 0), so that you can see it moving slowly.

**Comment by bitamirshafiee** [comment]
First I guessed it may be the problem, but no, I have the image on a horizontal plane, but still it is falling down, it gets smaller and smaller, I tried the gravity that you mentioned, and now it is not falling and getting smaller, and can be moved as I move the camera. but it is not moving it self(because I supposed that the animation that is being added and used by PhysicsController makes the Andy move by it self)
and yes I saw my debugging point right here 
augmentedImageRenderer.updateAndyPose(ballPose)
which ballPose has values.

**Comment by bitamirshafiee** [comment]
and could you please help me with the project build too?
when I clone the whole project android studio cannot configure it as an android studio project and cannot be run.
it says it needs to be configured. it seems it's not an android project.

**Comment by kai-dream** [comment]
Hi,

The github code is not the complete project, it only contains files we changed on top of ARCore Android SDK.

You need to
1) Download ARCore 1.23 SDK from Github (https://github.com/google-ar/arcore-android-sdk/releases)
2) Clone repository in this codelab, and copy files into ARCore 1.23 SDK.
3) Open the augmented_image_java sample using Android Studio.

**Comment by kai-dream** [comment]
> can be moved as I move the camera. but it is not moving it self

I don't understand that you mean. Maybe you can record the screen for a few seconds, and upload here so I can take a look.

> can be moved as I move the camera. 

Also, I am curious that you mean by this. A screen recording can help clarify. Note, you need to move the image to move the Andy on it.

**Comment by bitamirshafiee** [comment]
Sure, if you take a close look at the video you will see Andy is falling down.
You can find it in this link :
https://drive.google.com/file/d/1N1KFRjfCGcx85reydnLG3rAD3X33ECYO/view?usp=sharing

**Comment by kai-dream** [comment]
Thanks for the video.

It shows the maze object didn't hold the Android object, so that it falls through.

At least it means
* The jBullet physics engine is working
* The gravity is working at the right direction. (I guess you were pointing towards the floor when shooting this video).
* ARCore AugmentedImage API is working.

I don't know why that happens, because the Android object is supposed to be held (not falling) by a plane defined in PhysicsController.AddMazeRigidBody(). 

How to use a physics engine is quite complex and beyond the scope of this codelab. 
One thing I would try is try to lift the ballRB that represent the Android a bit higher on the maze.

In `PhysicsController.AddBallRigidBody()`, update 

```java
ballTransform.origin.set(0, 0.5f, 0); // Slightly raise the ball at the beginning
``` 

to


```java
ballTransform.origin.set(0, 1.0f, 0); // Change the height to 1.0
``` 

If that still doesn't solve your problem, maybe you can create a git repository, and upload your code there, so I can take a look to see what could be the reason.

**Comment by kai-dream** [comment]
Close the ticket due to no follow up action.

**Comment by putusugik** [comment]
Hi, its happen to me too, android object is still falling. 
Here my git repo: https://github.com/putusugik/ARCoreSample.git
