### ISSUE TITLE
Text changes in Codelab - https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#2

### ISSUE THREAD

**Issue by hmaw** [googlecodelabs/arcore-augmentedimage-intro#3]
Third page:

1. There is an area we can easily improve in this sample project: the image looks out of focus. 
This sentence reads a bit rough.  Suggested changes:
There is an area that is easily improved in this sample project: the image looks out of focus. 

2. The reason the image is out of focus is that ARCore camera sessions have the focus fixed at one meter by default.
Suggest: changing the have to has
The reason the image is out of focus is that the ARCore camera sessions has the focus fixed at one meter by default.

3.Now, let's give it a test run. This time we should be able to see the image being clearly focused in preview window. Like this:
Suggest:  remove the word being

Now, let's give it a test run. This time we should be able to see the image clearly focused in preview window. Like this:

**Comment by kai-dream** [comment]
Thanks for your suggestions.

I took suggestion 2 and 3.
For suggestion 1, I prefer to keep the active voice to highlight that it is something "we" to act on.

Cheers
Kai
