### ISSUE TITLE
Not able to find out the dimension of the model from OBJ file

### ISSUE THREAD

**Issue by dhananjaytrivedi-softway** [googlecodelabs/arcore-augmentedimage-intro#4]
Not able to refer the dimensions of the obj file as per the instructions which read:

One way to find out this is opening GreenMaze.obj in a text editor, get all the lines that begin with v, <x>, <y>, <z>, and get the maximum and minimum values of each component.

**Comment by kai-dream** [comment]
Hi,

Thank for raising the question. Indeed there's no good ways of doing this step, that was why I intentionally didn't mention. I'll update the description to explicitly say don't actually do it, but only explains how I get it. 

I actually get the max and min of each component using google sheets, after preprocessing data using bash script.

Cheers,
Kai

**Comment by kai-dream** [comment]
Done
