### ISSUE TITLE
This lab is not shown when I search for "Sceneform"

### ISSUE THREAD

**Issue by MrCsabaToth** [googlecodelabs/arcore-augmentedimage-intro#5]
Searching for `Sceneform` at [https://codelabs.developers.google.com/](https://codelabs.developers.google.com/) only yields the Intro lab. This Augmented Image demo only shows if I search for `ARCore`. I'd expect this lab to show as well upon a `Sceneform` keyword search, maybe even the other two ARCore demos as well? I guess some meta data / tags need to be adjusted somewhere.

**Comment by kai-dream** [comment]
Thanks for raising the issue. I'll follow up on how to make this codelab searchableb by "sceneform" keywords.

**Comment by kai-dream** [comment]
Hi, 

At the moment our codelabs.developers.google.com site doesn't support "tags". I'll revisit the issue when we have searchable tags.

Regards,
Kai

**Comment by MrCsabaToth** [comment]
What does the search work on? There must be some meta-data somewhere. Both the Sceneform and ARCore labs have the same icons.

**Comment by kai-dream** [comment]
The search works on codelab titles. The icon represents the category.  If you do filter by category (https://codelabs.developers.google.com/?cat=Augmented+Reality), you will find all ARCore codelabs.

**Comment by MrCsabaToth** [comment]
@kai-dream that's a sufficient workaround! We can possibly close this.

**Comment by kai-dream** [comment]
Ok, closing it for now. But I'll update it once we have that tag feature in the future.
