### ISSUE TITLE
setImage should also pay attention of the async material building is finished

### ISSUE THREAD

**Issue by MrCsabaToth** [googlecodelabs/arcore-augmentedimage-intro#7]
In special cases if the material building would be slower than the 3D model load, `setImage` (https://github.com/googlecodelabs/arcore-augmentedimage-intro/blob/master/sceneform-android-sdk-1.9.0/samples/augmentedimage/app/src/main/java/com/google/ar/sceneform/samples/augmentedimage/AugmentedImageNode.java#L75) could finish sooner than the material is created by the factory.

`makeOpaqueWithColor` is also returns a future:

    MaterialFactory.makeOpaqueWithColor(context, new Color(android.graphics.Color.RED))
        .thenAccept(
            material -> {
              ballRenderable =
                  ShapeFactory.makeSphere(0.01f, new Vector3(0, 0, 0), material); });

If someone also want to modify and play with the source in a way that it'd only contain object run-time built by the factories, then all the materials should be waited for at the beginning of the `setImage`. See also https://stackoverflow.com/questions/58032346/why-does-the-augmented-image-sceneform-sdk-sample-doesnt-work-only-with-run-tim

I may compile a PR if I'll have time. Basically the material has to be a private field and be watched on by the `CompletableFuture.allOf(` and the by the code above.

**Comment by kai-dream** [comment]
Hi,

Thanks for reporting this issue, and thanks for trying out this codelab!

The issue you raised make sense to me. Given Sceneform SDK is no longer part of ARCore's release package, I updated this codelab to be based on ARCore Android SDK augmented_image_java sample, removing the dependency of Sceneform. 

Regards
Kai

**Comment by MrCsabaToth** [comment]
Excellent. I haven't even mentioned the SceneForm archival. If someone has an existing project which worked before, and then upgrades to AndroidX, then follows Android Studio suggestion to upgrade the SceneForm plugin it causes exceptions. https://csaba.page/blog/sceneform-breaking-change.html

What will happen with codelabs like https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html ? It takes advantage for example of the TransformableNode which allows the user to relocate augmented objects pretty well.
