### ISSUE TITLE
Issues in "ARCore Augmented Images" codelab

### ISSUE THREAD

**Issue by omar-estrada** [googlecodelabs/arcore-augmentedimage-intro#8]
In step 3 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#3):

In the first code pane:

- There are some spelling errors:
  - `mazsScaleFactor` should be `mazeScaleFactor`
  - `mozeModelLocalOffset` should be `mazeModelLocalOffset`

- Some variables are snake_case (`maze_edge_size`, `maze_image_edge`) while others are camelCase.

- I was confused as to why `mazeRenderer.updateModelMatrix` had 4 args but Android Studio said it only needed 2. It wasn't until later that I realized that it was necessary to make the changes in ObjectRenderer.java for this to work.

In step 4 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#4):

- The instructions ask to add code to `AugmentedImageNode.java` but this file doesn't exist (it should be `AugmentedImageRenderer.java`).

In step 5 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#5):

- This is missing instructions to set up the SceneForm plugin as described [here](https://developers.google.com/sceneform/develop/getting-started). Otherwise, I get build errors in PhysicsController.java.

- I can't get the app to work as shown in the animation: the app doesn't show the maze or the planet image when it starts. Maybe there's some code missing in AugmentedImageActivity.java?

**Comment by kai-dream** [comment]
Hi, 

Thanks for pointing out the issues. I'll look into it.

Thanks,
Kai

**Comment by kai-dream** [comment]
Hi,

Sorry for the long delay. I finally got the time to update the codelab and addressed all your concerns except for the last point, as the codelab works for me.

**Details of modifications as below:**

> In step 3 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#3):
> 
> In the first code pane:
> 
> There are some spelling errors:
> 
> mazsScaleFactor should be mazeScaleFactor
> mozeModelLocalOffset should be mazeModelLocalOffset

Kai: Fixed, thanks for reminding!

> Some variables are snake_case (maze_edge_size, maze_image_edge) while others are camelCase.

Kai: Fixed, thanks.

> I was confused as to why mazeRenderer.updateModelMatrix had 4 args but Android Studio said it only needed 2. It wasn't until later that I realized that it was necessary to make the changes in ObjectRenderer.java for this to work.

Kai: Good point! I added more text to explain about this. 

> In step 4 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#4):
> 
> The instructions ask to add code to AugmentedImageNode.java but this file doesn't exist (it should be AugmentedImageRenderer.java).
> 

Kai: Thanks for pointing out. I updated them to AugmentedImageRenderer.java.

> In step 5 (https://codelabs.developers.google.com/codelabs/augimg-intro/index.html?index=..%2F..index#5):
> 
> This is missing instructions to set up the SceneForm plugin as described here. Otherwise, I get build errors in PhysicsController.java.

Kai: I forgot to update the link to PhysicsController.java. It should have been fixed in the newer version.

> I can't get the app to work as shown in the animation: the app doesn't show the maze or the planet image when it starts. Maybe there's some code missing in AugmentedImageActivity.java?

Kai: Please try again using latest codelab, it should work now with a few updated links.
